# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unac', '0002_auto_20170618_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=120, verbose_name='ciclo')),
                ('nombre', models.CharField(max_length=120, verbose_name='Curso')),
            ],
            options={
                'verbose_name_plural': 'Ciclos',
                'verbose_name': 'Ciclo',
            },
        ),
    ]
