# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unac', '0003_ciclo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=120, unique=True, verbose_name='Anio')),
            ],
            options={
                'verbose_name': 'Anio',
                'verbose_name_plural': 'Anios',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=120, verbose_name='Nota')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_set', to='unac.Alumnos')),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anio_set', to='unac.Anio')),
            ],
            options={
                'verbose_name': 'Notas',
                'verbose_name_plural': 'Notass',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='ciclo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ciclo_set', to='unac.Ciclo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='notas',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_set', to='unac.Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='notas',
            unique_together=set([('alumno', 'curso', 'anio')]),
        ),
    ]
