# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unac', '0005_auto_20170625_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='modificado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
    ]
