# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unac', '0007_auto_20170625_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anio',
            old_name='creatdo',
            new_name='creado',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
    ]
