# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unac', '0008_auto_20170625_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Escuela')),
                ('codigo', models.CharField(max_length=120, unique=True, verbose_name='Codigo')),
            ],
            options={
                'verbose_name_plural': 'Escuelas',
                'verbose_name': 'Escuela',
            },
        ),
        migrations.AddField(
            model_name='alumnos',
            name='escuela',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='escuela_alumnos', to='unac.Escuela'),
            preserve_default=False,
        ),
    ]
